name = "MotifScanner"
uuid = "20d16d9c-e052-46f5-8fae-7238198fc326"
authors = ["number-25 <swnt@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"

[compat]
BioSequences = "3.4.1"
FASTX = "2.1.7"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
